language: python
matrix:
  include:
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py34
      python: 3.4
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=pypy
      python: pypy-5.7.1
    - env: TOXENV=pre-commit
      python: 3.6
    - env: TOXENV=mypy
      python: 3.6
install:
  - pip install coveralls tox
script: tox
after_success: coveralls
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
deploy:
  provider: pypi
  user: syrusakbary
  on:
    tags: true
  password:
    secure: LHOp9DvYR+70vj4YVY8+JRNCKUOfYZREEUY3+4lMUpY7Zy5QwDfgEMXG64ybREH9dFldpUqVXRj53eeU3spfudSfh8NHkgqW7qihez2AhSnRc4dK6ooNfB+kLcSoJ4nUFGxdYImABc4V1hJvflGaUkTwDNYVxJF938bPaO797IvSbuI86llwqkvuK2Vegv9q/fy9sVGaF9VZIs4JgXwR5AyDR7FBArl+S84vWww4vTFD33hoE88VR4QvFY3/71BwRtQrnCMm7AOm31P9u29yi3bpzQpiOR2rHsgrsYdm597QzFKVxYwsmf9uAx2bpbSPy2WibunLePIvOFwm8xcfwnz4/J4ONBc5PSFmUytTWpzEnxb0bfUNLuYloIS24V6OZ8BfAhiYZ1AwySeJCQDM4Vk1V8IF6trTtyx5EW/uV9jsHCZ3LFsAD7UnFRTosIgN3SAK3ZWCEk5oF2IvjecsolEfkRXB3q9EjMkkuXRUeFDH2lWJLgNE27BzY6myvZVzPmfwZUsPBlPD/6w+WLSp97Rjgr9zS3T1d4ddqFM4ZYu04f2i7a/UUQqG+itzzuX5DWLPvzuNt37JB45mB9IsvxPyXZ6SkAcLl48NGyKok1f3vQnvphkfkl4lni29woKhaau8xlsuEDrcwOoeAsVcZXiItg+l+z2SlIwM0A06EvQ=
  distributions: "sdist bdist_wheel"
