language: python
sudo: false
python:
- 2.7
- 3.5
- 3.6
- "pypy-5.3.1"
before_install:
- |
  if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
    export PYENV_ROOT="$HOME/.pyenv"
    if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
      cd "$PYENV_ROOT" && git pull
    else
      rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
    fi
    export PYPY_VERSION="4.0.1"
    "$PYENV_ROOT/bin/pyenv" install "pypy-$PYPY_VERSION"
    virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
    source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
  fi
install:
- |
  if [ "$TEST_TYPE" = build ]; then
    pip install -e .[test]
    python setup.py develop
  elif [ "$TEST_TYPE" = lint ]; then
    pip install flake8
  elif [ "$TEST_TYPE" = mypy ]; then
    pip install mypy
  fi
script:
- |
  if [ "$TEST_TYPE" = lint ]; then
    echo "Checking Python code lint."
    flake8 graphene
    exit
  elif [ "$TEST_TYPE" = mypy ]; then
    echo "Checking Python types."
    mypy graphene
    exit
  elif [ "$TEST_TYPE" = build ]; then
    py.test --cov=graphene graphene examples
  fi
after_success:
- |
  if [ "$TEST_TYPE" = build ]; then
      coveralls
  fi
env:
  matrix:
  - TEST_TYPE=build
  global:
    secure: SQC0eCWCWw8bZxbLE8vQn+UjJOp3Z1m779s9SMK3lCLwJxro/VCLBZ7hj4xsrq1MtcFO2U2Kqf068symw4Hr/0amYI3HFTCFiwXAC3PAKXeURca03eNO2heku+FtnQcOjBanExTsIBQRLDXMOaUkf3MIztpLJ4LHqMfUupKmw9YSB0v40jDbSN8khBnndFykmOnVVHznFp8USoN5F0CiPpnfEvHnJkaX76lNf7Kc9XNShBTTtJsnsHMhuYQeInt0vg9HSjoIYC38Tv2hmMj1myNdzyrHF+LgRjI6ceGi50ApAnGepXC/DNRhXROfECKez+LON/ZSqBGdJhUILqC8A4WmWmIjNcwitVFp3JGBqO7LULS0BI96EtSLe8rD1rkkdTbjivajkbykM1Q0Tnmg1adzGwLxRUbTq9tJQlTTkHBCuXIkpKb1mAtb/TY7A6BqfnPi2xTc/++qEawUG7ePhscdTj0IBrUfZsUNUYZqD8E8XbSWKIuS3SHE+cZ+s/kdAsm4q+FFAlpZKOYGxIkwvgyfu4/Plfol4b7X6iAP9J3r1Kv0DgBVFst5CXEwzZs19/g0CgokQbCXf1N+xeNnUELl6/fImaR3RKP22EaABoil4z8vzl4EqxqVoH1nfhE+WlpryXsuSaF/1R+WklR7aQ1FwoCk8V8HxM2zrj4tI8k=
matrix:
  fast_finish: true
  include:
  - python: '2.7'
    env: TEST_TYPE=lint
  - python: '3.6'
    env: TEST_TYPE=mypy
deploy:
  provider: pypi
  user: syrusakbary
  on:
    tags: true
  password:
    secure: LHOp9DvYR+70vj4YVY8+JRNCKUOfYZREEUY3+4lMUpY7Zy5QwDfgEMXG64ybREH9dFldpUqVXRj53eeU3spfudSfh8NHkgqW7qihez2AhSnRc4dK6ooNfB+kLcSoJ4nUFGxdYImABc4V1hJvflGaUkTwDNYVxJF938bPaO797IvSbuI86llwqkvuK2Vegv9q/fy9sVGaF9VZIs4JgXwR5AyDR7FBArl+S84vWww4vTFD33hoE88VR4QvFY3/71BwRtQrnCMm7AOm31P9u29yi3bpzQpiOR2rHsgrsYdm597QzFKVxYwsmf9uAx2bpbSPy2WibunLePIvOFwm8xcfwnz4/J4ONBc5PSFmUytTWpzEnxb0bfUNLuYloIS24V6OZ8BfAhiYZ1AwySeJCQDM4Vk1V8IF6trTtyx5EW/uV9jsHCZ3LFsAD7UnFRTosIgN3SAK3ZWCEk5oF2IvjecsolEfkRXB3q9EjMkkuXRUeFDH2lWJLgNE27BzY6myvZVzPmfwZUsPBlPD/6w+WLSp97Rjgr9zS3T1d4ddqFM4ZYu04f2i7a/UUQqG+itzzuX5DWLPvzuNt37JB45mB9IsvxPyXZ6SkAcLl48NGyKok1f3vQnvphkfkl4lni29woKhaau8xlsuEDrcwOoeAsVcZXiItg+l+z2SlIwM0A06EvQ=
  distributions: "sdist bdist_wheel"
